# Generated by Django 4.1.2 on 2024-07-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password1', models.CharField(default='', max_length=100)),
                ('password2', models.CharField(default='', max_length=100)),
                ('telefono', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
